name: Compress Images on Push to main branch
on:
  push:
    branches:
      - master
    paths:
      - 'Web/**'

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.PAT }}
          compressOnly: true
          ignorePaths: '!(Web)/**'
          
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
          
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
