name: Optimize website images
on:
  push:
    branches:
      - master
    paths:
      - 'Web/**'

permissions:
  contents: write
  
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Configure git
        run: |
          git config user.name "ChrisWhite1024"
          git config user.email "chriswhite33333@gmail.com"
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.TINIFY_API_KEY }}
          path: 'Web/'
